### ISSUE TITLE
¿Qué haces como proteccionista de animales?

### ISSUE THREAD

**Issue by hernanprego** [pdep-utn-frd/presentacion-francohilt#1]

**Comment by francohilt** [comment]
Un Protector o proteccionista de animales se rige por un principio claro y simple: el respeto a la dignidad del animal.
Luchamos por la aprobación de leyes que ayuden al bienestar de los animales maltratados y/o abandonados.
Actualmente soy difusor del Refugio ZAGUATES, en el cual rescatamos animales abandonados, los curamos y ofrecemos adopción responsable a personas que realmente sean consientes que un animal necesita su cuidado, atención y cariño.
